---

## No gpg signature: https://github.com/composer/composer/issues/38
## https://composer.github.io/pubkeys.html
## https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
- name: Download Composer installer.
  ansible.builtin.get_url:
    url: "{{ item.u }}"
    dest: "{{ item.d }}"
    mode: "{{ item.m }}"
  with_items: "{{ misp_composer_dl }}"

- name: Get installer checksum
  ansible.builtin.stat:
    path: /tmp/composer-installer.php
    checksum_algorithm: sha384
  register: installer
- name: Get signature hash
  ansible.builtin.command: cat /tmp/installer.sig
  register: installersig
  changed_when: false
  ignore_errors: true

- name: Composer signature
  when: installer.stat.checksum != installersig.stdout
  block:
    - name: Debug | installer var
      ansible.builtin.debug:
        var: installer.stat.checksum
    - name: Debug | installersig var
      ansible.builtin.debug:
        var: installersig.stdout
    - name: Check composer signature
      ansible.builtin.fail:
        msg: "FATAL! composer signature not matching."

- name: Install composer
  ansible.builtin.command: "{{ php_bin | default('php') }} -q /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer"
  args:
    creates: /usr/local/bin/composer
  environment: COMPOSER_HOME="/usr/local/bin"
  
- name: Install composers components
  block:
    - name: Allow-plugins composer/installers as required
      community.general.composer:
        command: config
        arguments: allow-plugins.composer/installers true
        working_dir: "{{ misp_rootdir }}/app"
        executable: "{{ php_bin | default(omit) }}"
      register: pkg_result
      until: pkg_result is success
      become: yes
      become_user: "{{ www_user }}"

    - name: Install PHP dependencies via composer (kamisama/cake-resque, Vendor)
      community.general.composer:
        command: install
        working_dir: "{{ misp_rootdir }}/app"
        executable: "{{ php_bin | default(omit) }}"
      register: pkg_result
      until: pkg_result is success
      become: yes
      become_user: "{{ www_user }}"
  rescue:
    - name: Composer diagnose
      community.general.composer:
        command: diagnose
        working_dir: "{{ misp_rootdir }}/app"
        executable: "{{ php_bin | default(omit) }}"
      register: pkg_result
      until: pkg_result is success
      failed_when: false
      become: yes
      become_user: "{{ www_user }}"
    - name: Composer global diagnose
      community.general.composer:
        command: global
        arguments: diagnose
        working_dir: "{{ misp_rootdir }}/app"
        executable: "{{ php_bin | default(omit) }}"
      register: pkg_result
      until: pkg_result is success
      failed_when: false
      become: yes
      become_user: "{{ www_user }}"
    - name: Composer version profile
      community.general.composer:
        command: ""
        arguments: --version --profile -vvv --no-interaction
        working_dir: "{{ misp_rootdir }}/app"
        executable: "{{ php_bin | default(omit) }}"
      register: pkg_result
      until: pkg_result is success
      become: yes
      become_user: "{{ www_user }}"
